// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVcnuvIL64Vq951BCIKGTpt_cK1m5kwVY',
    appId: '1:238322390076:web:b767373177b7c4a2ad9f39',
    messagingSenderId: '238322390076',
    projectId: 'learning-platform-d82cd',
    authDomain: 'learning-platform-d82cd.firebaseapp.com',
    storageBucket: 'learning-platform-d82cd.appspot.com',
    measurementId: 'G-H62DCFWMES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSzlg8Qt6HQyraiBnz4s18biZISbtkL3E',
    appId: '1:238322390076:android:cca14bdba0903385ad9f39',
    messagingSenderId: '238322390076',
    projectId: 'learning-platform-d82cd',
    storageBucket: 'learning-platform-d82cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7M0E-lOw2x-YFPuhpSEb98-vO17klGlQ',
    appId: '1:238322390076:ios:052bedb6be040299ad9f39',
    messagingSenderId: '238322390076',
    projectId: 'learning-platform-d82cd',
    storageBucket: 'learning-platform-d82cd.appspot.com',
    iosBundleId: 'com.example.learningPtalform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7M0E-lOw2x-YFPuhpSEb98-vO17klGlQ',
    appId: '1:238322390076:ios:3a8fd7799623217fad9f39',
    messagingSenderId: '238322390076',
    projectId: 'learning-platform-d82cd',
    storageBucket: 'learning-platform-d82cd.appspot.com',
    iosBundleId: 'com.example.learningPtalform.RunnerTests',
  );
}
